# Workflow info
name: First Workflow
on:
  [workflow_dispatch, push]

# Jobs Level
jobs:
  first-job:
    runs-on: ubuntu-latest

    steps:  # Step Level
      - name: Print
        run : 
          echo "Hello World"
      
      - name: Print goodbye
        run:
          echo "Bye bye!"